name: CI SPA

on:
  push:
    branches: ["**"]
    paths-ignore:
      - "**/**.md"
      - "**/.gitignore"
      - "**/.gitattributes"
      - "**/.vs/**"
      - "**/.vscode/**"
      - "scripts/**"
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build SPA

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node Environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: ./src
      - name: Install packages
        run: npm ci
        working-directory: ./src
      - name: Lint
        run: npm run lint --if-present
        working-directory: ./src
      - name: Build Angular
        run: npm run build --if-present
        working-directory: ./src
      - name: Run tests
        run: npm run test:headless --if-present
        working-directory: ./src
      - name: Build Storybook
        run: npm run build-storybook --if-present
        working-directory: ./src
